### ISSUE TITLE
Support for PHP v 8.x

### ISSUE THREAD

**Issue by ghost** [gaalferov/ext-domain-connect#10]
Getting the following error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - layershifter/tld-extract 2.0.1 requires php ^5.5.0 || ^7.0 -> your php version (8.2.0) does not satisfy that requirement.
    - gaalferov/php-ext-domain-connect[1.0, ..., 1.3] require layershifter/tld-extract ^2.0 -> satisfiable by layershifter/tld-extract[2.0.1].
    - Root composer.json requires gaalferov/php-ext-domain-connect * -> satisfiable by gaalferov/php-ext-domain-connect[1.0, 1.1, 1.2, 1.3].

**Comment by gaalferov** [comment]
@argonaut1 I will update within a week

**Comment by gaalferov** [comment]
I see that some libraries "layershifter/tld-extract" doesn't support PHP 8 so not sure that can update at the last PHP version

**Comment by ghost** [comment]
Right, it is seems deprecated, according to message on the repository:

"DEPRECATED
Consider to use https://github.com/jeremykendall/php-domain-parser as
maintained alternative. "

**Comment by ghost** [comment]
Any chance you can use the above maintained alternative in your code? Thanks.

**Comment by gaalferov** [comment]
Added support of PHP 8.0 and above
